In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\LENOVO\IPL_Cricket_Analysis\IPL_Data.csv")

In [4]:
# View first 5 rows
df.head()

,Name,Team,Url,Type,ValueinCR,Full Name,Born,Age,National Side,Batting Style,...,Maidens,RunsConceded,Wickets,Best,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
0,Mayank Agarwal,PBKS,https://sports.ndtv.com/cricket/players/1430-m...,Batsman,12.00,Mayank Anurag Agarwal,"February 16, 1991 Bangalore, Karnataka","31 Years, 0 Months, 28 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Liam Livingstone,PBKS,https://sports.ndtv.com/cricket/players/64363-...,All-Rounder,11.50,Liam Stephen Livingstone,"August 4, 1993 Barrow-in-Furness, Cumberland","28 Years, 7 Months, 11 Days",England,Right Handed,...,0.0,13.0,0.0,0/13 v MI,0.0,0.0,NaN,13.00,NaN,1.0
2,Kagiso Rabada,PBKS,https://sports.ndtv.com/cricket/players/64042-...,Bowler,9.25,Kagiso Rabada,"May 25, 1995 Johannesburg","26 Years, 9 Months, 22 Days",South Africa,Left Handed,...,2.0,1560.0,76.0,4/21 v RCB,4.0,0.0,20.52,8.21,15.0,50.0
3,Shahrukh Khan,PBKS,https://sports.ndtv.com/cricket/players/113433...,All-Rounder,9.00,Masood Shahrukh Khan,"May 27, 1995 Chennai, Tamil Nadu","26 Years, 9 Months, 20 Days",India,Right Handed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Shikhar Dhawan,PBKS,https://sports.ndtv.com/cricket/players/737-sh...,Batsman,8.25,Shikhar Dhawan,"December 5, 1985 Delhi","36 Years, 3 Months, 10 Days",India,Left Handed,...,0.0,66.0,4.0,1/7 v DC,0.0,0.0,16.50,8.25,12.0,6.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 39 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             237 non-null    str
 1   Team             237 non-null    str
 2   Url              237 non-null    str
 3   Type             237 non-null    str
 4   ValueinCR        237 non-null    float64
 5   Full Name        231 non-null    str
 6   Born             231 non-null    str
 7   Age              231 non-null    str
 8   National Side    231 non-null    str
 9   Batting Style    227 non-null    str
 10  Bowling          206 non-null    str
 11  Sport            126 non-null    str
 12  MatchPlayed      162 non-null    float64
 13  InningsBatted    162 non-null    float64
 14  NotOuts          162 non-null    float64
 15  RunsScored       153 non-null    float64
 16  HighestInnScore  153 non-null    str
 17  100s             162 non-null    float64
 18  50s              162 non-null    float64
 19  4s               162 non-null    float64
 20  6s               162 non-null    float64
 21  BattingAVG       145 non-null    float64
 22  BattingS/R       162 non-null    float64
 23  CatchesTaken     145 non-null    float64
 24  StumpingsMade    145 non-null    float64
 25  Ducks            161 non-null    float64
 26  R/O              161 non-null    float64
 27  InningsBowled    122 non-null    float64
 28  Overs            122 non-null    float64
 29  Maidens          122 non-null    float64
 30  RunsConceded     122 non-null    float64
 31  Wickets          122 non-null    float64
 32  Best             122 non-null    str
 33  3s               122 non-null    float64
 34  5s               122 non-null    float64
 35  BowlingAVG       105 non-null    float64
 36  EconomyRate      122 non-null    float64
 37  S/R              105 non-null    float64
 38  Mtc              122 non-null    float64
dtypes: float64(26), str(13)
memory usage: 72.3 KB

In [6]:
df.isnull().sum()

Name                 0
Team                 0
Url                  0
Type                 0
ValueinCR            0
Full Name            6
Born                 6
Age                  6
National Side        6
Batting Style       10
Bowling             31
Sport              111
MatchPlayed         75
InningsBatted       75
NotOuts             75
RunsScored          84
HighestInnScore     84
100s                75
50s                 75
4s                  75
6s                  75
BattingAVG          92
BattingS/R          75
CatchesTaken        92
StumpingsMade       92
Ducks               76
R/O                 76
InningsBowled      115
Overs              115
Maidens            115
RunsConceded       115
Wickets            115
Best               115
3s                 115
5s                 115
BowlingAVG         132
EconomyRate        115
S/R                132
Mtc                115
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop_duplicates()
print("Duplicate rows removed successfully!")

Duplicate rows removed successfully!

In [9]:
df.isnull().sum()

Name                 0
Team                 0
Url                  0
Type                 0
ValueinCR            0
Full Name            6
Born                 6
Age                  6
National Side        6
Batting Style       10
Bowling             31
Sport              111
MatchPlayed         75
InningsBatted       75
NotOuts             75
RunsScored          84
HighestInnScore     84
100s                75
50s                 75
4s                  75
6s                  75
BattingAVG          92
BattingS/R          75
CatchesTaken        92
StumpingsMade       92
Ducks               76
R/O                 76
InningsBowled      115
Overs              115
Maidens            115
RunsConceded       115
Wickets            115
Best               115
3s                 115
5s                 115
BowlingAVG         132
EconomyRate        115
S/R                132
Mtc                115
dtype: int64

In [10]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

print("Missing values filled successfully!")

Missing values filled successfully!

In [11]:
df.isnull().sum()

Name                 0
Team                 0
Url                  0
Type                 0
ValueinCR            0
Full Name            6
Born                 6
Age                  6
National Side        6
Batting Style       10
Bowling             31
Sport              111
MatchPlayed          0
InningsBatted        0
NotOuts              0
RunsScored           0
HighestInnScore     84
100s                 0
50s                  0
4s                   0
6s                   0
BattingAVG           0
BattingS/R           0
CatchesTaken         0
StumpingsMade        0
Ducks                0
R/O                  0
InningsBowled        0
Overs                0
Maidens              0
RunsConceded         0
Wickets              0
Best               115
3s                   0
5s                   0
BowlingAVG           0
EconomyRate          0
S/R                  0
Mtc                  0
dtype: int64

In [12]:
df = df.dropna()
print("Remaining rows:", len(df))

Remaining rows: 113

In [13]:
df.isnull().sum()

Name               0
Team               0
Url                0
Type               0
ValueinCR          0
Full Name          0
Born               0
Age                0
National Side      0
Batting Style      0
Bowling            0
Sport              0
MatchPlayed        0
InningsBatted      0
NotOuts            0
RunsScored         0
HighestInnScore    0
100s               0
50s                0
4s                 0
6s                 0
BattingAVG         0
BattingS/R         0
CatchesTaken       0
StumpingsMade      0
Ducks              0
R/O                0
InningsBowled      0
Overs              0
Maidens            0
RunsConceded       0
Wickets            0
Best               0
3s                 0
5s                 0
BowlingAVG         0
EconomyRate        0
S/R                0
Mtc                0
dtype: int64

In [14]:
df.to_csv("Cleaned_IPL_Data.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [16]:
df.describe()

,ValueinCR,MatchPlayed,InningsBatted,NotOuts,RunsScored,100s,50s,4s,6s,BattingAVG,...,Overs,Maidens,RunsConceded,Wickets,3s,5s,BowlingAVG,EconomyRate,S/R,Mtc
count,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,...,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000
mean,4.927876,50.398230,31.380531,8.601770,585.097345,0.123894,3.185841,51.283186,22.769912,15.659962,...,112.417699,0.893805,897.256637,31.743363,2.061947,0.097345,34.731448,8.651593,25.073477,34.230088
std,4.307365,50.683461,44.463733,10.265702,1239.449921,0.656462,9.089386,117.705782,46.592843,10.300829,...,132.709176,1.638612,1011.087814,39.093473,2.994886,0.326360,18.124500,1.808342,12.545709,37.960978
min,0.200000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.100000,0.000000,2.000000,0.000000,0.000000,0.000000,5.000000,5.000000,6.000000,1.000000
25%,1.000000,13.000000,6.000000,2.000000,23.000000,0.000000,0.000000,1.000000,0.000000,7.500000,...,14.000000,0.000000,105.000000,4.000000,0.000000,0.000000,25.260000,7.610000,19.480000,5.000000
50%,4.000000,34.000000,14.000000,6.000000,69.000000,0.000000,0.000000,5.000000,3.000000,14.300000,...,68.300000,0.000000,562.000000,17.000000,1.000000,0.000000,30.900000,8.290000,22.600000,24.000000
75%,8.000000,72.000000,32.000000,12.000000,370.000000,0.000000,1.000000,29.000000,14.000000,22.620000,...,150.000000,1.000000,1247.000000,43.000000,3.000000,0.000000,34.760000,9.040000,25.050000,47.000000
max,16.000000,213.000000,208.000000,63.000000,6283.000000,5.000000,50.000000,654.000000,227.000000,41.590000,...,583.000000,9.000000,4061.000000,167.000000,14.000000,2.000000,153.000000,18.000000,108.000000,171.000000

In [17]:
summary = df.describe()
summary.to_csv("Summary_Report.csv")

print("Summary report saved successfully!")

Summary report saved successfully!

In [20]:
with pd.ExcelWriter("IPL_Report.xlsx") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)
    summary.to_excel(writer, sheet_name="Summary")

print("Excel report created successfully!")

Excel report created successfully!

In [21]:
df.to_csv("Cleaned_IPL_Data.csv", index=False)